controller_manager:
  ros__parameters:
    update_rate: 225  # Hz
    use_sim_time: true

    ar4_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    impedance_controller:
      type: impedance_controller/ImpedanceController

    ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

ar4_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - ar4_joint_1
      - ar4_joint_2
      - ar4_joint_3
      - ar4_joint_4
      - ar4_joint_5
      - ar4_joint_6
      

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

velocity_controller:
  ros__parameters:
    joints:
      - ar4_joint_1
      - ar4_joint_2
      - ar4_joint_3
      - ar4_joint_4
      - ar4_joint_5
      - ar4_joint_6

impedance_controller:
  ros__parameters:
    joints:
      - ar4_joint_1
      - ar4_joint_2
      - ar4_joint_3
      - ar4_joint_4
      - ar4_joint_5
      - ar4_joint_6
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

# ets_state_broadcaster:
#   ros__parameters:
#     sensor_name: external_torque_sensor
